-- Migration to update client statuses from uncertain/potential/ongoing/completed to new/ongoing/completed
-- Migration to update client statuses from uncertain/potential/ongoing/completed to new/ongoing/completed

-- Safely drop any existing CHECK constraint on the `status` column (handles unknown autogenerated names)
DO $$
DECLARE
  conname TEXT;
BEGIN
  SELECT con.conname
  INTO conname
  FROM pg_constraint con
  WHERE con.conrelid = 'clients'::regclass
    AND con.contype = 'c'
    AND pg_get_constraintdef(con.oid) ILIKE '%status%';

  IF conname IS NOT NULL THEN
    EXECUTE format('ALTER TABLE clients DROP CONSTRAINT %I', conname);
  END IF;
END$$;

-- Now update existing rows: map old statuses to 'new'
UPDATE clients SET status = 'new' WHERE status IN ('uncertain', 'potential');

-- Add new constraint with updated statuses
ALTER TABLE clients ADD CONSTRAINT clients_status_check
  CHECK (status IN ('new', 'ongoing', 'completed'));

-- Update the default value to 'new'
ALTER TABLE clients ALTER COLUMN status SET DEFAULT 'new';

-- Add comment to document the status meanings
COMMENT ON COLUMN clients.status IS 'Client status: new (new inquiries), ongoing (active projects), completed (finished projects)';
